;Piece data format:
; . . . . C T T T
; 7 6 5 4 3 2 1 0
;
; C = color (1 (8?) = white, 0 = black)
; T = piece type

PIECE_NONE := 0

PIECE_KING := 1
PIECE_QUEEN := 2
PIECE_ROOK := 3
PIECE_BISHOP := 4
PIECE_KNIGHT := 5
PIECE_PAWN := 6

PIECE_WHITE := 8
PIECE_BLACK := 0

MASK_PIECE_TYPE := 0111b
MASK_PIECE_COLOR := 1000b

;castle flag definitions

CASTLE_FLAG_WHITE_KING := 0001b
CASTLE_FLAG_WHITE_QUEEN := 0010b
CASTLE_FLAG_BLACK_KING := 0100b
CASTLE_FLAG_BLACK_QUEEN := 1000b

MASK_CASTLE_WHITE := 0011b
MASK_CASTLE_BLACK := 1100b

;move flag definitions

MOVE_FLAG_NONE := 0
MOVE_FLAG_PROMOTE_QUEEN := 1
MOVE_FLAG_PROMOTE_ROOK := 2
MOVE_FLAG_PROMOTE_BISHOP := 3
MOVE_FLAG_PROMOTE_KNIGHT := 4
MOVE_FLAG_DOUBLE_PAWN := 5
MOVE_FLAG_EN_PASSANT := 6
MOVE_FLAG_KINGSIDE_CASTLE := 7
MOVE_FLAG_QUEENSIDE_CASTLE := 8

;other

EN_PASSANT_NONE := 255   ;since 0-7 is used for storing valid ep files it's not 0
