    MOVE_FLAG_NONE := 0
    MOVE_FLAG_PROMOTE_QUEEN := 1
    MOVE_FLAG_PROMOTE_ROOK := 2
    MOVE_FLAG_PROMOTE_BISHOP := 3
    MOVE_FLAG_PROMOTE_KNIGHT := 4
    MOVE_FLAG_DOUBLE_PAWN := 5
    MOVE_FLAG_EN_PASSANT := 6
    MOVE_FLAG_KINGSIDE_CASTLE := 7
    MOVE_FLAG_QUEENSIDE_CASTLE := 8

    